### ISSUE TITLE
Search crash

### ISSUE THREAD

**Issue by colbycdev** [teocci/YouTube-In-Background#12]
Whenever I searched a video, that app immediately crashes

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cckole** [comment]
### Description

When I first launched the app and searched for a video on YouTube, the app crashed. I relaunched and searched again and I was able to search for the videos I wanted. After exiting the app for some hours and going back to search. It crashes again before picking up. I noticed this action several times and I discovered that when ever the app is settled and visited after a while, it first crash before working well.

### Expected behavior

I expected to search for videos on youtube freely at any time without the app crashing at first initiation after exiting for a while.

### Steps to reproduce 

After launching the app

- Click on the search icon at the top and type the name of the video you want to search. You might note the crash if you are using it for the first time. If not, exit the app and revisit after few hours following the same steps. You will definitely note the crash.


### Reproducing the behavior

https://youtu.be/EG2Bp0ZQ4fA

### Device used

- Techno spark K7
- Android 7.0 O.S
- App version: 

### Logcat

```FATAL EXCEPTION: main
05-26 17:38:59.052  2176  2176 E AndroidRuntime: Process: com.teocci.ytinbg, PID: 2176
05-26 17:38:59.052  2176  2176 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.teocci.ytinbg.adapters.VideosAdapter.clearYouTubeVideos()' on a null object reference
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at com.teocci.ytinbg.ui.fragments.SearchFragment.searchQuery(SearchFragment.java:190)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at com.teocci.ytinbg.ui.MainActivity.handleIntent(MainActivity.java:488)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at com.teocci.ytinbg.ui.MainActivity.onNewIntent(MainActivity.java:282)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1235)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2865)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.ActivityThread.performNewIntents(ActivityThread.java:2877)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2886)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.ActivityThread.-wrap15(ActivityThread.java)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:110)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6251)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-26 17:38:59.052  2176  2176 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)```
