### ISSUE TITLE
Error Extracting Audio

### ISSUE THREAD

**Issue by Jeffersonceo** [teocci/YouTube-In-Background#22]
`01-30 17:07:32.633 8846-9043/com.teocci.ytinbg:youtube W/System.err: Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
01-30 17:07:34.026 8846-9043/com.teocci.ytinbg:youtube W/System.err: java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:519)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:457)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:241)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:36)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-30 17:07:34.027 8846-9043/com.teocci.ytinbg:youtube W/System.err:     at java.lang.Thread.run(Thread.java:818)`

**Comment by Jeffersonceo** [comment]
Erro YouTube Extractor
